### ISSUE TITLE
cmus

### ISSUE THREAD

**Issue by emninger** [stephen-huan/dotfiles#2]
Hi!

Thanks a lot for your nice examples and instructions! And thanks you pointed me to cmus ...

In this regard, a qustion: How can i set cmus to play just a single track when opening it in ranger - like mplayer for example does? The only way i see is, to add first the entire directory to a playlist (using the "5" cmd) ... (?)

TIA

**Comment by stephen-huan** [comment]
Hello,

I'm not familiar with mplayer and not sure why you're using cmus in ranger (to play an audio file)? If so, you can use cmus's commands, documented in the "COMMANDS" section of the man page, and accessible through the executable `cmus-remote`. `cmus-remote -q music.mp3` should add the file to the play queue and `cmus-remote -p` will start playing the track. I think you can edit ranger's `rifle` to use those cmus-remote commands and launch cmus. 

Hope that was helpful

**Comment by emninger** [comment]
It's a bit late, but yes! Thanks!
