### ISSUE TITLE
Move Finder

### ISSUE THREAD

**Issue by kabirbg** [stephen-huan/dotfiles#3]
Hello! Thank you so much for your advice on disabling the DE and default macOS apps. You say that running `sudo mount -uw /` should allow you to move Finder despite the read-only System partition; however, this produces the following error for me: 
`mount_apfs: volume could not be mounted: Permission denied`
`mount: / failed with 66`
Any suggestions on how to get around this would be appreciated. I also tried elevating to root with `su` and running the command but had the same issue; I'm on macOS Big Sur (11.1).

**Comment by stephen-huan** [comment]
"System Integrity Protection (SIP) needs to be disabled but that's a given for Yabai to work well."
Try `csrutil status`, it should say "System Integrity Protection status: disabled."  If SIP isn't disabled, follow the instructions at https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection. 

I'm not sure whether you can modify system files on Big Sur, maybe Apple locked the filesystem down even more.

**Comment by kabirbg** [comment]
thanks! i did try that and ran it again just now; SIP is disabled. even despite that it didn't let me mount the system partition, which is weird... possibly a Big Sur issue like you said. Also, when disabling the DE is there supposed to be any notable visual differences i notice? because i disabled following your instructions and nothing *seems* to have changed...

**Comment by stephen-huan** [comment]
I think the desktop environment just refers to whether the folders/files in the `~/Desktop` folder are shown on the background: with CreateDesktop true
![image](https://user-images.githubusercontent.com/20411956/103074106-ebe50d80-4596-11eb-940c-36ac52fe39da.png)
with CreateDesktop false:
![image](https://user-images.githubusercontent.com/20411956/103074158-0c14cc80-4597-11eb-92e8-8d15a50c8c4a.png)

`sudo mount -uw /` works for me on Catalina 10.15.7 so it's probably a Big Sur issue.

**Comment by kabirbg** [comment]
Ok, thanks so much for your help! Makes sense; I'll mark the issue as closed then since it just appears to be an Apple problem. Thank you again!
