### ISSUE TITLE
Remove animation when switching spaces

### ISSUE THREAD

**Issue by hotsno** [stephen-huan/dotfiles#4]
Hey, I just watched your Yabai demonstration video and was wondering how you disabled the animation for switching between workspaces and also set up keybinds to switch windows between spaces. I'm guessing these things might be integrated into Yabai and I'm sorry if they are, I'm not quite ready to switch to it yet but wanted to know what exactly was allowing you to do this.

**Comment by stephen-huan** [comment]
I mention in [MacOS tips](https://github.com/stephen-huan/dotfiles/blob/master/doc/macos.md) to "Minimize transitions by System Preferences -> Accessibility -> Display -> Reduce motion" but I think that only applies to MacOS ways of switching spaces (e.g. you can move left/right with ctrl + left/right arrow, if reduce motion is off it has a big swiping animation and if reduce motion is on it becomes a more subtle fade-out fade-in transition).

Yabai might naturally disable space switching transitions if you use its command line API:
`yabai -m space --focus 1` to switch to space 1, `yabai -m space --focus prev`/`yabai -m space --focus next` for the left and right space from the current space, and `yabai -m space --focus recent` for the most recent previous space. 

I use a seperate program, [skhd](https://github.com/koekeishiya/skhd), to bind keyboard keys to those commands.
